### ISSUE TITLE
Event system

### ISSUE THREAD

**Issue by donbonifacio** [orionsbelt-battlegrounds/game#3]
This is part of the [v0.1 milestone](https://github.com/orionsbelt-battlegrounds/game/wiki/v0.1).

We need an event system to manage the game events. This system will be responsible for registering listeners and notifying them of changes. We need an indirection that will be able to:

- [x] Subscribe to the lobby - get the current lobby anytime a new lobby game is changed
- [x] Subscribe to a specific game

The implementation should:

- [x] Be an independent module at `src/obb/events`
- [x] Be a [Component](https://github.com/stuartsierra/component)
- [x] Have a `core.async` interface

The talked about implementation should be in process memory.

**Comment by quimrstorres** [comment]
@donbonifacio , I think this still reflects your previous iteration on this subject. Will you write down the new strategy over here?

**Comment by donbonifacio** [comment]
@quimrstorres yes, I'll update this and add that _url_ flow to this.
